server:
  port: 8083
spring:
  application:
    name: realty-management-system-property-service
    version: 1.0.0
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://${CONFIG_SERVICE_USERNAME}:${CONFIG_SERVICE_PASSWORD}@${CONFIG_SERVICE_HOST}:8888/